name: quiz_quest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  bonfire: ^3.13.3
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  equatable: ^2.0.7
  enum_to_string: ^2.2.0
  meta: ^1.15.0
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/data/museumData/
  - assets/images/items/
  - assets/images/tiled/
  - assets/images/ui/
  - assets/images/player/character_1/
  - assets/images/player/character_2/
  - assets/images/player/character_3/
  - assets/images/player/character_4/
  - assets/images/player/character_5/
  - assets/images/player/character_6/
  - assets/data/playerData/
  - assets/data/quizData/
  
  fonts:
  - family: Pixel
    fonts:
    - asset: fonts/Pixel.ttf